services:
    _defaults:
        autowire: true
        autoconfigure: true

    Callisto\CallistoMailer\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/CallistoMailerBundle.php'
            - '../src/Controller/'
            - '../src/Event/'
            - '../src/Exception/'
